first_commit_for_graduation_exam_part_implemention
hiro97617/mokumoku pull request #3
Opened 2023-03-27 07:26 UTC by hiro97617

こちらが実装したものになります。
下記に、RSpecを実施したスクリーンショットを添付してあります。
ご確認のほど、よろしくお願いします。
<img width="1135" alt="mokumoku_rspec_cleat" src="https://user-images.githubusercontent.com/113866577/227870202-95d298be-d105-4234-827f-6286349e8708.png">

2023-03-27 10:06 UTC, busitora approved these changes

2023-03-27 10:06 UTC, busitora commented on app/controllers/events_controller.rb
> +  def gender_check
@event のインスタンスに対し チェックを行う場合、コントローラーではなくモデルメソッドに寄せて、かつテストを書きましょう。

2023-03-27 10:06 UTC, busitora commented on app/controllers/events_controller.rb
> +    if @event.save && @event.gender_check
if @event.gender_check なら save ならわかるのですが、 && にしている理由を説明いただいて大丈夫でしょうか？？

2023-03-27 10:06 UTC, busitora commented on app/controllers/events_controller.rb
> +
無駄な空白は追加しないようにしましょう！

2023-03-27 10:06 UTC, busitora commented on app/models/user.rb
> +  enum gender: {other:0, man:1, woman:2}
```suggestion
  enum gender: { other:0, man:1, woman:2 }
```

nits : の方がキレイですね

2023-03-27 10:06 UTC, busitora commented on app/views/events/show.html.erb
> +                <% if current_user.gender == woman && @event.only_woman %>
if がネストしていますので、こちらの Logic を モデルメソッドに寄せてみてください。

2023-03-29 07:51 UTC, hiro97617 commented
２回目のプルリクエストを行いました。ご確認のほど、よろしくお願いします。
スクリーンショットも添付いたします。
<img width="531" alt="rspec_test" src="https://user-images.githubusercontent.com/113866577/228464287-39fd1e7e-14c2-4d7e-8c78-ca1cb8ab56cb.png">

2023-03-30 10:05 UTC, busitora requested changes

2023-03-30 10:05 UTC, busitora commented on app/models/event.rb
> +  def gender_check(event)
event.only_woman == true || event.only_woman == false

↑ こちら、 bool の true false をどちらも定義しているのはなぜですか?

もし XX && YY || ZZ なら、  (XX && YY) としてください

2023-03-30 11:40 UTC, hiro97617 commented
ご教授ありがとうございます。
ご教授に基づき、修正しましたので、ご確認のほど、よろしくお願いします。
<img width="531" alt="1a80d30dc350afbbf0d409803ad3767e" src="https://user-images.githubusercontent.com/113866577/228824960-d6ed0b8c-b96e-45d4-af64-1c440adf5168.png">

2023-03-30 12:15 UTC, busitora requested changes

2023-03-31 03:51 UTC, hiro97617 commented
命名の直しをしました。
また、そのメソッドでXX && YY || ZZという形になっていたので、
そちらの修正も行いました。
ご確認のほど、よろしくお願いします。

2023-03-31 10:31 UTC, takyyk commented
修正確認しました！
LGTMです！

2023-04-01 07:48 UTC, merged